#!/usr/bin/env bash
# configure.sh — Apply shell config, symlinks, and hooks (no package installs).
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Git configuration is managed by chezmoi (aiwilliams/home) as of the Phase 3
# cutover: ~/.gitconfig is a template, ~/.config/git/personal carries the
# per-path identity override, and ~/.ssh/allowed_signers is regenerated by a
# run_onchange_ script. lib/ssh-signing-key.sh is left in the tree unused so
# reverting this commit restores the previous behavior.

# bin/ and its runtime lib/ dependencies moved to the aiwilliams/home repo as of
# the Phase 3 cutover; chezmoi owns the ~/.local/bin symlinks. The installer
# lib/*.sh files stay here — install-{macos,ubuntu}.sh still source postgres.sh
# and clickhouse.sh, which now live in the home repo, so those two scripts are
# broken until Phase 3 step 5 ports them to .chezmoiscripts/.

# tmux config is managed by chezmoi (aiwilliams/home) as of the Phase 3 cutover.

# Zsh config (.zshenv, .zshrc, .p10k.zsh, and the zmx oh-my-zsh plugin) is
# managed by chezmoi (aiwilliams/home) as of the Phase 3 cutover.

# Set zsh as default shell (macOS already uses zsh)
if [ "$(uname -s)" = "Linux" ]; then
  ZSH_PATH="$(which zsh)"
  if [ "$(getent passwd "$USER" | cut -d: -f7)" != "$ZSH_PATH" ]; then
    echo "Changing default shell to zsh..."
    sudo chsh -s "$ZSH_PATH" "$USER"
  fi
fi

# The global gitignore (~/.config/git/ignore) is managed by chezmoi
# (aiwilliams/home) as of the Phase 3 cutover.

# Pre-commit hook
ln -sf "$SCRIPT_DIR/hooks/pre-commit" "$SCRIPT_DIR/.git/hooks/pre-commit"
echo "Installed pre-commit hook"

# Claude Code statusline
mkdir -p "$HOME/.claude"
ln -sf "$SCRIPT_DIR/config/claude/statusline-command.sh" "$HOME/.claude/statusline-command.sh"
CLAUDE_SETTINGS="$HOME/.claude/settings.json"
if [ ! -f "$CLAUDE_SETTINGS" ]; then
  echo '{}' > "$CLAUDE_SETTINGS"
fi
jq '.statusLine = {"type": "command", "command": "bash ~/.claude/statusline-command.sh"}' \
  "$CLAUDE_SETTINGS" > "$CLAUDE_SETTINGS.tmp" && mv "$CLAUDE_SETTINGS.tmp" "$CLAUDE_SETTINGS"
echo "Configured Claude Code statusline"

# The *-ansi themes render diff context and dimmed text from the terminal's
# bright-black ANSI slot, which collapses to near-invisible on dark Ghostty
# backgrounds. Normalize to the fixed-RGB equivalents (which carry their own
# contrast) while preserving each machine's light/dark preference.
jq '(.theme) |= (if . == "dark-ansi" then "dark" elif . == "light-ansi" then "light" else . end)' \
  "$CLAUDE_SETTINGS" > "$CLAUDE_SETTINGS.tmp" && mv "$CLAUDE_SETTINGS.tmp" "$CLAUDE_SETTINGS"
echo "Normalized Claude Code theme (no *-ansi)"

# Claude Code MCP servers
source "$SCRIPT_DIR/lib/claude-mcp.sh"

# Symlink AGENTS.md to AI tool config directories
source "$SCRIPT_DIR/lib/agents.sh"
