#!/usr/bin/env bash
# configure.sh — Apply shell config, symlinks, and hooks (no package installs).
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Git configuration is managed by chezmoi (aiwilliams/home) as of the Phase 3
# cutover: ~/.gitconfig is a template, ~/.config/git/personal carries the
# per-path identity override, and ~/.ssh/allowed_signers is regenerated by a
# run_onchange_ script. lib/ssh-signing-key.sh is left in the tree unused so
# reverting this commit restores the previous behavior.

# bin/ and its runtime lib/ dependencies moved to the aiwilliams/home repo as of
# the Phase 3 cutover; chezmoi owns the ~/.local/bin symlinks. The installer
# lib/*.sh files stay here — install-{macos,ubuntu}.sh still source postgres.sh
# and clickhouse.sh, which now live in the home repo, so those two scripts are
# broken until Phase 3 step 5 ports them to .chezmoiscripts/.

# tmux config is managed by chezmoi (aiwilliams/home) as of the Phase 3 cutover.

# Zsh config (.zshenv, .zshrc, .p10k.zsh, and the zmx oh-my-zsh plugin) is
# managed by chezmoi (aiwilliams/home) as of the Phase 3 cutover.

# Set zsh as default shell (macOS already uses zsh)
if [ "$(uname -s)" = "Linux" ]; then
  ZSH_PATH="$(which zsh)"
  if [ "$(getent passwd "$USER" | cut -d: -f7)" != "$ZSH_PATH" ]; then
    echo "Changing default shell to zsh..."
    sudo chsh -s "$ZSH_PATH" "$USER"
  fi
fi

# The global gitignore (~/.config/git/ignore) is managed by chezmoi
# (aiwilliams/home) as of the Phase 3 cutover.

# Pre-commit hook
ln -sf "$SCRIPT_DIR/hooks/pre-commit" "$SCRIPT_DIR/.git/hooks/pre-commit"
echo "Installed pre-commit hook"

# The Claude Code statusline is managed by chezmoi (aiwilliams/home) as of the
# Phase 5 cutover, rendered into every profile from one shared body. The theme
# normalization that lived here was a one-off already applied to settings.json.
#
# Both blocks began with `mkdir -p "$HOME/.claude"`, as did lib/agents.sh. After
# Phase 5d that single line is destructive: it re-creates the directory whose
# ABSENCE is the tripwire for a session that escaped the profile dispatcher.
# lib/agents.sh is deleted for the same reason — and because the two symlinks it
# installed had been dangling since July, pointing at lib/AGENTS.md when the file
# is at the repo root.

# Claude Code MCP servers
source "$SCRIPT_DIR/lib/claude-mcp.sh"
