#!/usr/bin/env bash
# configure.sh — Apply shell config, symlinks, and hooks (no package installs).
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Git configuration is managed by chezmoi (aiwilliams/home) as of the Phase 3
# cutover: ~/.gitconfig is a template, ~/.config/git/personal carries the
# per-path identity override, and ~/.ssh/allowed_signers is regenerated by a
# run_onchange_ script. lib/ssh-signing-key.sh is left in the tree unused so
# reverting this commit restores the previous behavior.

# Symlink db-worktree CLI to ~/.local/bin
mkdir -p "$HOME/.local/bin"
ln -sf "$SCRIPT_DIR/bin/db-worktree" "$HOME/.local/bin/db-worktree"
ln -sf "$SCRIPT_DIR/bin/wt" "$HOME/.local/bin/wt"
ln -sf "$SCRIPT_DIR/bin/pg" "$HOME/.local/bin/pg"
ln -sf "$SCRIPT_DIR/bin/cmux-ws" "$HOME/.local/bin/cmux-ws"
ln -sf "$SCRIPT_DIR/bin/syshealth" "$HOME/.local/bin/syshealth"
ln -sf "$SCRIPT_DIR/bin/scope" "$HOME/.local/bin/scope"
ln -sf "$SCRIPT_DIR/bin/swapsize" "$HOME/.local/bin/swapsize"
ln -sf "$SCRIPT_DIR/bin/tsgo-shim" "$HOME/.local/bin/tsgo-shim"
ln -sf "$SCRIPT_DIR/bin/env-init" "$HOME/.local/bin/env-init"
ln -sf "$SCRIPT_DIR/bin/env-revert" "$HOME/.local/bin/env-revert"
echo "Symlinked db-worktree, wt, pg, cmux-ws, syshealth, scope, swapsize, tsgo-shim, env-init, env-revert to ~/.local/bin/"

# tmux config is managed by chezmoi (aiwilliams/home) as of the Phase 3 cutover.

# Zsh config
ln -sf "$SCRIPT_DIR/config/zsh/.zshenv" "$HOME/.zshenv"
ln -sf "$SCRIPT_DIR/config/zsh/.zshrc" "$HOME/.zshrc"
ln -sf "$SCRIPT_DIR/config/zsh/.p10k.zsh" "$HOME/.p10k.zsh"
ln -sfn "$SCRIPT_DIR/config/zsh/plugins/zmx" "${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/zmx"
echo "Symlinked .zshenv, .zshrc, .p10k.zsh, and zmx plugin to ~/"

# Set zsh as default shell (macOS already uses zsh)
if [ "$(uname -s)" = "Linux" ]; then
  ZSH_PATH="$(which zsh)"
  if [ "$(getent passwd "$USER" | cut -d: -f7)" != "$ZSH_PATH" ]; then
    echo "Changing default shell to zsh..."
    sudo chsh -s "$ZSH_PATH" "$USER"
  fi
fi

# The global gitignore (~/.config/git/ignore) is managed by chezmoi
# (aiwilliams/home) as of the Phase 3 cutover.

# Pre-commit hook
ln -sf "$SCRIPT_DIR/hooks/pre-commit" "$SCRIPT_DIR/.git/hooks/pre-commit"
echo "Installed pre-commit hook"

# Claude Code statusline
mkdir -p "$HOME/.claude"
ln -sf "$SCRIPT_DIR/config/claude/statusline-command.sh" "$HOME/.claude/statusline-command.sh"
CLAUDE_SETTINGS="$HOME/.claude/settings.json"
if [ ! -f "$CLAUDE_SETTINGS" ]; then
  echo '{}' > "$CLAUDE_SETTINGS"
fi
jq '.statusLine = {"type": "command", "command": "bash ~/.claude/statusline-command.sh"}' \
  "$CLAUDE_SETTINGS" > "$CLAUDE_SETTINGS.tmp" && mv "$CLAUDE_SETTINGS.tmp" "$CLAUDE_SETTINGS"
echo "Configured Claude Code statusline"

# The *-ansi themes render diff context and dimmed text from the terminal's
# bright-black ANSI slot, which collapses to near-invisible on dark Ghostty
# backgrounds. Normalize to the fixed-RGB equivalents (which carry their own
# contrast) while preserving each machine's light/dark preference.
jq '(.theme) |= (if . == "dark-ansi" then "dark" elif . == "light-ansi" then "light" else . end)' \
  "$CLAUDE_SETTINGS" > "$CLAUDE_SETTINGS.tmp" && mv "$CLAUDE_SETTINGS.tmp" "$CLAUDE_SETTINGS"
echo "Normalized Claude Code theme (no *-ansi)"

# Claude Code MCP servers
source "$SCRIPT_DIR/lib/claude-mcp.sh"

# Symlink AGENTS.md to AI tool config directories
source "$SCRIPT_DIR/lib/agents.sh"
