# Powerlevel10k instant prompt (must stay near top of .zshrc)
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# --- Oh My Zsh ---

export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="powerlevel10k/powerlevel10k"
plugins=(git zsh-autosuggestions zsh-syntax-highlighting)
source "$ZSH/oh-my-zsh.sh"

# --- Environment ---

export NX_TUI=false

# --- Aliases ---

alias vim=nvim

# --- Platform-specific ---

case "$(uname -s)" in
  Linux)
    # pbcopy via OSC 52 (works over SSH + tmux)
    alias pbcopy='printf "\033]52;c;%s\a" "$(base64)"'
    # SSH key via keychain
    eval "$(keychain --eval --agents ssh id_ed25519_$(hostname))"
    ;;
esac

# --- Tools ---

eval "$(~/.local/bin/mise activate zsh)"

# --- Local overrides (not version-controlled) ---

[[ -f ~/.zshrc.local ]] && source ~/.zshrc.local

# Powerlevel10k config (generated by `p10k configure`)
[[ -f ~/.p10k.zsh ]] && source ~/.p10k.zsh
