# Powerlevel10k instant prompt (must stay near top of .zshrc)
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# --- Oh My Zsh ---

export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="powerlevel10k/powerlevel10k"
plugins=(git zmx zsh-autosuggestions zsh-syntax-highlighting)
source "$ZSH/oh-my-zsh.sh"

# --- Environment ---

export PNPM_HOME="$HOME/.local/share/pnpm"
export PATH="$HOME/.local/bin:$PNPM_HOME:$PATH"
export NX_TUI=false

# --- Aliases & Functions ---

# Neovim v0.11+ sends a DA1 query (\e[c) during its exit cleanup, just before
# leaving the alternate screen. Over SSH, the round-trip to Ghostty means the
# response (\e[?62;22;52c) arrives after neovim has exited, so it leaks to the
# shell prompt as "62;22;52c". Wrapping nvim in a function that briefly drains
# stdin after exit catches these stale terminal responses. The 50ms timeout
# covers typical SSH round-trip latency; on a local terminal the drain is
# near-instant. Type-ahead is not a concern here since users don't pre-type
# commands while still inside vim.
vim() {
  command nvim "$@"
  local _byte
  while read -t 0.05 -k 1 _byte 2>/dev/null; do :; done
}

# Wrap wt so that `wt switch` can cd in the current shell
wt() {
  case "${1:-}" in
    switch|main)
      local dir
      dir=$(command wt "$@") || return
      [[ -n "$dir" ]] && cd "$dir"
      ;;
    create|checkout)
      rm -f /tmp/wt_cd_path
      command wt "$@" || return
      [[ -f /tmp/wt_cd_path ]] && cd "$(</tmp/wt_cd_path)" && rm -f /tmp/wt_cd_path
      ;;
    *)
      command wt "$@"
      ;;
  esac
}

# --- Platform-specific ---

case "$(uname -s)" in
  Linux)
    # pbcopy via OSC 52 (works over SSH + tmux)
    alias pbcopy='printf "\033]52;c;%s\a" "$(base64)"'
    # SSH key via keychain
    eval "$(keychain --eval --quiet --agents ssh id_ed25519_$(hostname))"
    ;;
esac

# --- Terminal fixups ---

# TUI programs (Claude Code, neovim) may push the kitty keyboard protocol
# and/or enable xterm modifyOtherKeys without properly restoring on exit,
# leaving Ctrl-C, Ctrl-R, etc. emitting raw CSI u sequences. Pop up to 99
# kitty protocol stack entries and reset modifyOtherKeys before each prompt.
_reset_keyboard_protocol() { printf '\e[<99u\e[>4;0m' >/dev/tty; }
precmd_functions+=(_reset_keyboard_protocol)

# --- Tools ---

eval "$(mise activate zsh)"

# --- Local overrides (not version-controlled) ---

[[ -f ~/.zshrc.local ]] && source ~/.zshrc.local

# Powerlevel10k config (generated by `p10k configure`)
[[ -f ~/.p10k.zsh ]] && source ~/.p10k.zsh
